name: "format"

on:
  push:
    branches: [main]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set-up Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
          components: rustfmt, clippy

      - name: Test clippy lints
        run: cargo clippy --all -- -D warnings

      - name: Test format
        run: cargo +nightly fmt --all --check
