name: "format"

on:
  push:
    branches: [main]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set-up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: llvm-tools-preview

