name: format

on:
  push:
    branches: [main]
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set-up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy

#      clippy is broken, claims syn types don't implement debug
#      - name: Test clippy lints
#        run: cargo clippy --all -- -D warnings

      - name: Test format
        run: cargo +nightly fmt --all --check
