# This action will keep track of the current crate verision, the last
# pushed git tag and determine whether the project should be deployed
#
# Additionally it will keep track whether THE LAST TAG has a release
# assigned, if it doesn't unless otherwise specified it will attempt
# to create one.

name: publish

on:
  workflow_run:
    workflows:
      - tests
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success'
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write

    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          npm-packages: "semver"

      - name: Get And Parse Repository Versions
        id: versions
        if: success()
        run: |
          # The version of the main crate which should be the first on the list in the workspace config.
          echo "crate_version=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')" \
            >> $GITHUB_OUTPUT;

          # The last pushed git tag if any.
          last_git_tag="$(git describe --tags --abbrev=0 || echo '')";
          if [[ -z "$last_git_tag" ]]; then exit 0; fi;
          echo "last_tag=$last_git_tag" >> $GITHUB_OUTPUT;


      - name: Determine What Should Be Done
        id: to_do
        if: success()
        run: |
          crate_version="${{ steps.versions.outputs.crate_version }}";
          last_tag="${{ steps.versions.outputs.last_tag }}";

          # If there is no last tag, make up 0.0.0.
          if [ -z "$last_tag" ]; then
            last_tag="0.0.0"
          fi

          # If the last published tag is minor than the crate's tag
          # determine that the crate should be published.
          if semver -r "> $last_tag" "$crate_version"; then
            echo "should_publish='true'" >> $GITHUB_OUTPUT
          else
            echo "should_publish='false'" >> $GITHUB_OUTPUT
          fi

          # If there is no release associated to the last tag
          # determine that a release should be created.
          if ! gh release view "$last_tag" >/dev/null 2>&1; then
            echo "should_release=true" >> $GITHUB_OUTPUT;
          else
            echo "should_release=false" >> $GITHUB_OUTPUT;
          fi


      - name: Publish And Create A New Tag
        if: success() && steps.to_do.outputs.should_publish == 'true'
        run: |
          # If cargo publish fails a new release won't be made.
          # Make sure that it exits in case github actions doesn't halt.
          cargo publish || exit 1;

          git tag ${{ steps.versions.outputs.crate_version }};
          git push origin ${{ steps.versions.outputs.crate_version }};


      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        if: success() && steps.to_do.outputs.should_release == 'true'
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose --latest --strip header

      - name: Create Release
        uses: actions/create-release@v1
        if: success() && steps.to_do.outputs.should_release == 'true'
        with:
          tag_name: ${{ steps.versions.outputs.last_tag }}
          release_name: Release ${{ steps.versions.outputs.crate_version }}
          body: ${{ steps.git-cliff.outputs.content }}
          draft: false
          prerelease: false
